import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="logo">
            <div id="logo">
              <a href="">
                <img id="logo-image" alt="POLYWOOD Scheduler" />
              </a>
            </div>
          </div>
          <div id="header-right-container"></div>
        </header>
        {children}
        <footer>
        POLYWOOD&reg; Saber Tooth v 1.1 |
        Git Data [Branch: next-js |
        Commit Hash: 5589ddc63f24aadc93ffac4f71524295f5ae9b37 |
        Version Date: 2026-08-01 00:00:01] |
        DB [saber-tooth-db.polywood_scheduler] |
        Acumatica [Polywood lcl dev]
      </footer>
      </body>
    </html>
  );
}
